### ISSUE TITLE
Source for coco pre-trained model

### ISSUE THREAD

**Issue by natlouis** [zgspose/DSTA#4]
Hi, thank you for making this code available. In the [Base_PoseTrack17.yaml](https://github.com/zgspose/DSTA/blob/main/configs/posetimation/DSTA/Base_PoseTrack17.yaml#L31) config file, what is the source for the pre-trained model you use? `/code/DSTA/checkpoints/coco-laplace-rle.pth`
Are those weights available for download?

**Comment by zgspose** [comment]
The pre-trained weights are obtained using the RLE method, which you can find at https://github.com/Jeff-sjtu/res-loglikelihood-regression.
